global_costmap:
   global_frame: map
   robot_base_frame: base_link
   update_frequency: 4.0
   publish_frequency: 3.0
   static_map: true
   rolling_window: false
   resolution: 0.01
   transform_tolerance: 1.0
   map_type: costmap
   inflation_radius: 0.78
