GlobalPlanner:

  allow_unknown: true
  default_tolerance: 0.2

  visualize_potential: false

  use_dijkstra: true

  use_quadratic: true

  use_grid_path: false

  old_navfn_behavior: false

 

  lethal_cost: 180

  neutral_cost: 40

  cost_factor: 3.0

  publish_potential: true

  orientation_mode: 0

  orientation_window_size: 1
