shutdown_costmaps: false
controller_frequency: 5.0
controller_patience: 3.0
planner_frequency: 2.5
planner_patience: 5.0
oscillation_timeout: 8.0
oscillation_distance: 0.3
#base_local_planner: "dwa_local_planner/DWAPlannerROS"
#base_global_planner: "global_planner/GlobalPlanner"
